<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__slider</name>
   <tag></tag>
   <elementGuidId>f0800ba0-c225-44b9-8302-3abc4ae58451</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='main']/app-root/ngx-pages/ngx-sample-layout/nb-layout/div/div/nb-layout-header/nav/ngx-header/div[2]/div/div/ngx-layout-direction-switcher/ngx-switcher/label/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.slider</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slider</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/app-root[1]/ngx-pages[@class=&quot;ng-tns-c228-0 ng-star-inserted&quot;]/ngx-sample-layout[@class=&quot;ng-tns-c228-0&quot;]/nb-layout[@class=&quot;window-mode with-scroll&quot;]/div[@class=&quot;scrollable-container&quot;]/div[@class=&quot;layout&quot;]/nb-layout-header[@class=&quot;fixed&quot;]/nav[@class=&quot;fixed&quot;]/ngx-header[1]/div[@class=&quot;header-container&quot;]/div[@class=&quot;settings-row&quot;]/div[@class=&quot;switcher&quot;]/ngx-layout-direction-switcher[1]/ngx-switcher[1]/label[@class=&quot;switch-label&quot;]/div[@class=&quot;switch&quot;]/span[@class=&quot;slider&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='main']/app-root/ngx-pages/ngx-sample-layout/nb-layout/div/div/nb-layout-header/nav/ngx-header/div[2]/div/div/ngx-layout-direction-switcher/ngx-switcher/label/div/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
   </webElementXpaths>
</WebElementEntity>
