<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_(empty)</name>
   <tag></tag>
   <elementGuidId>fb476e0c-e50a-47e9-9d9b-a0d4c64211d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div[3]/div/div/div[3]/div/a/span[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ajax_cart_no_product</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9790dec7-bb0f-45eb-a2e6-ba8adf41987d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ajax_cart_no_product</value>
      <webElementGuid>55285696-db0e-47ee-94db-680f96ca90a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(empty)</value>
      <webElementGuid>2137a1f0-0859-4c67-b410-9686caa627b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[3]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-4 clearfix&quot;]/div[@class=&quot;shopping_cart&quot;]/a[1]/span[@class=&quot;ajax_cart_no_product&quot;]</value>
      <webElementGuid>537e349e-fe41-4491-bd9f-3f9b2da9a129</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div[3]/div/div/div[3]/div/a/span[5]</value>
      <webElementGuid>a300cbe8-58ab-482a-adcc-ae7247a94090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products'])[1]/following::span[2]</value>
      <webElementGuid>a7f85c76-569c-41d4-9bf9-09094b355737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product'])[1]/following::span[3]</value>
      <webElementGuid>6e8e2b47-05e7-4480-bff8-c588f457a4f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free shipping!'])[1]/preceding::span[1]</value>
      <webElementGuid>a9c148a7-300c-4566-80fd-aeb8732f640a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipping'])[1]/preceding::span[2]</value>
      <webElementGuid>b03715a4-7f36-4155-ba5f-7d2073e067f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='(empty)']/parent::*</value>
      <webElementGuid>bde9fea0-e9f2-4525-b0e1-76dcbd764420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]</value>
      <webElementGuid>e5b5b164-a401-4108-8526-a64576449320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '(empty)' or . = '(empty)')]</value>
      <webElementGuid>456a6756-49e5-4b4c-9355-c9e8950dd53b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
