<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>circle</name>
   <tag></tag>
   <elementGuidId>01e71e0d-8b34-4164-a89b-3502e6ac079e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ExplorerContainer&quot;)/div[@class=&quot;Explorer&quot;]/div[@class=&quot;ExplorerFigure&quot;]/div[@class=&quot;GrapherComponent&quot;]/div[3]/svg[1]/g[@class=&quot;LineChart&quot;]/g[@class=&quot;hoverIndicator&quot;]/circle[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>671bbf27-7b47-4d6a-9d79-4378d3a0cb8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>210</value>
      <webElementGuid>51c87524-4ba2-4ca8-a05b-c09a63e876ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>328.3</value>
      <webElementGuid>7aaa16ea-0eeb-4561-aacf-45281509a1b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>4.25</value>
      <webElementGuid>c2c667ae-f796-46e8-9ed2-ce0941dd5214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#6D3E91</value>
      <webElementGuid>32332212-bc40-400c-bec0-3776b58c034b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>#fff</value>
      <webElementGuid>f83c4cc6-6114-4d28-9038-b1e6a3739972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>0.5</value>
      <webElementGuid>fe474214-3604-4511-b89d-d4ffa9ccf0e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExplorerContainer&quot;)/div[@class=&quot;Explorer&quot;]/div[@class=&quot;ExplorerFigure&quot;]/div[@class=&quot;GrapherComponent&quot;]/div[3]/svg[1]/g[@class=&quot;LineChart&quot;]/g[@class=&quot;hoverIndicator&quot;]/circle[4]</value>
      <webElementGuid>bf539ebb-f062-48a9-9b9b-44e3a181881b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
