<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>circle_1_2</name>
   <tag></tag>
   <elementGuidId>38df185f-7d48-46ce-8500-fc98f5b84e9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ExplorerContainer&quot;)/div[@class=&quot;Explorer&quot;]/div[@class=&quot;ExplorerFigure&quot;]/div[@class=&quot;GrapherComponent&quot;]/div[3]/svg[1]/g[@class=&quot;LineChart&quot;]/g[@class=&quot;hoverIndicator&quot;]/circle[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>d80d4250-5053-4675-80e9-a2cd7f32fb71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>342</value>
      <webElementGuid>9503a49e-cfa3-40ce-bebf-62103638d183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>318.2</value>
      <webElementGuid>13d31b23-1558-4fa4-958a-2f7b8a87de1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>4.25</value>
      <webElementGuid>b8e713d0-8fff-43a8-b43a-0fbc31e9600d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#00823F</value>
      <webElementGuid>be208386-6d10-4962-b251-77d5ec6769e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>#fff</value>
      <webElementGuid>f26884a1-de2a-42a7-a7ae-a5ab79a1b522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>0.5</value>
      <webElementGuid>35d45527-0273-492e-8c0e-b947172790f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExplorerContainer&quot;)/div[@class=&quot;Explorer&quot;]/div[@class=&quot;ExplorerFigure&quot;]/div[@class=&quot;GrapherComponent&quot;]/div[3]/svg[1]/g[@class=&quot;LineChart&quot;]/g[@class=&quot;hoverIndicator&quot;]/circle[7]</value>
      <webElementGuid>ae3421de-ab38-436d-adab-cdb379d098d8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
