<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>circle_1</name>
   <tag></tag>
   <elementGuidId>eb0abefb-21da-4ac2-af01-8e15506bc5e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ExplorerContainer&quot;)/div[@class=&quot;Explorer&quot;]/div[@class=&quot;ExplorerFigure&quot;]/div[@class=&quot;GrapherComponent&quot;]/div[3]/svg[1]/g[@class=&quot;LineChart&quot;]/g[@class=&quot;hoverIndicator&quot;]/circle[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>dbcd47e5-26b8-4e16-ac0c-0382b326d1b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>243.9</value>
      <webElementGuid>9ddeb6d0-b23a-4242-b2ab-df955eaf8332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>320.4</value>
      <webElementGuid>7753408a-e2da-4628-a27a-959728c4ea37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>4.25</value>
      <webElementGuid>22b56ca1-e821-4f69-95be-e3cb5574aa48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#883039</value>
      <webElementGuid>eadbfe5a-b12e-495f-887f-12bfb5df1d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>#fff</value>
      <webElementGuid>a96de6f5-0ff8-4a16-bbcf-882a12bd62a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>0.5</value>
      <webElementGuid>28a5fd8c-4b75-456e-9acc-20e5156be522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExplorerContainer&quot;)/div[@class=&quot;Explorer&quot;]/div[@class=&quot;ExplorerFigure&quot;]/div[@class=&quot;GrapherComponent&quot;]/div[3]/svg[1]/g[@class=&quot;LineChart&quot;]/g[@class=&quot;hoverIndicator&quot;]/circle[6]</value>
      <webElementGuid>55f45226-7a28-4aa1-88bf-f79027b2063a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
