<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>line</name>
   <tag></tag>
   <elementGuidId>8ff54b12-97ff-4e0b-be7b-1c75a6787ded</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ExplorerContainer&quot;)/div[@class=&quot;Explorer&quot;]/div[@class=&quot;ExplorerFigure&quot;]/div[@class=&quot;GrapherComponent&quot;]/div[3]/svg[1]/g[@class=&quot;LineChart&quot;]/g[@class=&quot;hoverIndicator&quot;]/line[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>g.hoverIndicator > line</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>line</value>
      <webElementGuid>9dc89284-78dd-45fd-a3e8-38ca807acdb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x1</name>
      <type>Main</type>
      <value>145.1</value>
      <webElementGuid>a125799a-e208-4a26-b58a-cfac508f12f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y1</name>
      <type>Main</type>
      <value>370.6</value>
      <webElementGuid>ff22e72e-141e-4298-b4ce-31035ed8a9fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x2</name>
      <type>Main</type>
      <value>145.1</value>
      <webElementGuid>26977fc9-2540-40ab-a4e6-bbf6b39981ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y2</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>d83c0e9c-dcf1-4e9f-85de-1e5c60415f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>rgba(180,180,180,.4)</value>
      <webElementGuid>2fedbd65-0381-4c4c-bb3d-52591f6679e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExplorerContainer&quot;)/div[@class=&quot;Explorer&quot;]/div[@class=&quot;ExplorerFigure&quot;]/div[@class=&quot;GrapherComponent&quot;]/div[3]/svg[1]/g[@class=&quot;LineChart&quot;]/g[@class=&quot;hoverIndicator&quot;]/line[1]</value>
      <webElementGuid>152a435f-e8ff-402d-bd65-c84435abdbc6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
